/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package reader;

import java.io.IOException;
import java.util.List;
import java.util.Map;

public class App {
    public static void main(String[] args) throws IOException, InterruptedException {

        if (args.length != 1) {
            System.out.println("Missing url");
            System.exit(1);
        }
        String url = args[0];
        Reader reader = new ReaderImpl();
        Map<String, List<Content>> widgetSummaryList = reader.read(url);
        Printer printer = new PrintImpl(new Output() {
            @Override
            public void init() {
            }

            @Override
            public void write(String s) {
                System.out.println(s);
            }

            @Override
            public void close() {
            }
        });
        printer.print(widgetSummaryList);
        System.exit(0);
    }

    public String getGreeting() {
        return "Hello World!";
    }
}
